version: 2
jobs:
  test-e2e:
    docker:
      - image: circleci/node:jessie-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install && cd ./test-e2e && npm install
      - run:
          name: Running Tests
          command: |
            npm run test-e2e
      - run:
          name: Repo Check 2
          command: |
              npm run test-e2e:browserstack
      - store_artifacts:
          path: /tmp/test-errors
workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - test-e2e
