version: 2
jobs:
  test-e2e-login:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Repo Check 1
          command: |
              export BROWSERSTACK_AUTH="gacop1:5NmFByapv6gexSQfKyTK"
              npm install && npm run test-e2e:browserstack
            fi
      - store_artifacts:
          path: /tmp/test-errors
workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - build
      - test-e2e-login
